### ISSUE TITLE
Scaffolding has been supported in 1.1.0-rtm-10004

### ISSUE THREAD

**Issue by Kagamine** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#121]
① Add Design-time layer and EF Core tools to your project (>= 1.1.0-rtm-10003):

```json
"Pomelo.EntityFrameworkCore.MySql": "1.1.0-rtm-10004",
"Pomelo.EntityFrameworkCore.MySql.Design": "1.1.0-rtm-10004",
"Microsoft.EntityFrameworkCore.Tools": "1.1.0-preview4-final"
```

② Using the tool to execute scaffolding commands
```
dotnet ef dbcontext scaffold "Server=localhost;User Id=root;Password=123456;Database=eftests" "Pomelo.EntityFrameworkCore.MySql" -o Models
```

![image](https://cloud.githubusercontent.com/assets/2216750/20511425/5db52ab2-b0b3-11e6-84d8-20f9da38286a.png)

![image](https://cloud.githubusercontent.com/assets/2216750/20511446/7c31df1c-b0b3-11e6-908f-23da5fb44405.png)

**Comment by mguinness** [comment]
@Kagamine This is awesome!  Thanks for your efforts.  Just a note that you also need the following in your project.json file if that isn't already there.

`"tools": {
  "Microsoft.EntityFrameworkCore.Tools.DotNet": "1.1.0-preview4",
}`

I did notice something which may be an issue.  When I compared this to scaffolding from SQL Server it appears to be missing the navigation properties.  

<pre>
public partial class Offices
{
    <b>public Offices()
    {
        Employees = new HashSet<Employees>();
    }</b>

    public string OfficeCode { get; set; }
    public string City { get; set; }
    public string Phone { get; set; }
    public string AddressLine1 { get; set; }
    public string AddressLine2 { get; set; }
    public string State { get; set; }
    public string Country { get; set; }
    public string PostalCode { get; set; }
    public string Territory { get; set; }

    <b>public virtual ICollection<Employees> Employees { get; set; }</b>
}
</pre>

**Comment by Kagamine** [comment]
It should be fixed in 10004, if not, please open an issue thx.

**Comment by mguinness** [comment]
Thanks for your quick response and the fix.  It does appear to work partially, but some are still missing.  If you use the database sample at http://www.mysqltutorial.org/mysql-sample-database.aspx I've outlined the differences below:

**Customers.cs**
missing `Orders = new HashSet<Orders>();` in ctor
member `Orders Orders` should be `ICollection<Orders> Orders`

**Employees.cs**
missing `Customers = new HashSet<Customers>();` in ctor
member `Customers Customers` should be `ICollection<Customers> Customers`
member `Employees InverseReportsToNavigation` should be `ICollection<Employees> InverseReportsToNavigation`

**Offices.cs**
missing `Employees = new HashSet<Employees>();` in ctor
member `Employees Employees` should be `ICollection<Employees> Employees`

**Productlines**
missing `Products = new HashSet<Products>();` in ctor
member `Products Products` should be `ICollection<Products> Products`
member `public string HtmlDescription { get; set; }` missing
member `public byte[] Image { get; set; }` missing

**Products.cs**
missing `Orderdetails = new HashSet<Orderdetails>();` in ctor
member `Orderdetails Orderdetails` should be `ICollection<Orderdetails> Orderdetails`

**Comment by Kagamine** [comment]
@mguinness Fixed in 1.1.0-rtm-10007

**Comment by mguinness** [comment]
Thanks!  Almost there, used 1.1.0-rtm-10008 but the following members aren't generated.

**Productlines.cs**
member `public string HtmlDescription { get; set; }` missing
member `public byte[] Image { get; set; }` missing

Below is the table definition, maybe the datatypes used for those fields is the problem.

<pre>
CREATE TABLE `productlines` (
	`productLine` VARCHAR(50) NOT NULL,
	`textDescription` VARCHAR(4000) NULL DEFAULT NULL,
	`htmlDescription` MEDIUMTEXT NULL,
	`image` MEDIUMBLOB NULL,
	PRIMARY KEY (`productLine`)
)
COLLATE='latin1_swedish_ci'
</pre>

**Comment by Kagamine** [comment]
@mguinness Fixed in 10009

**Comment by caleblloyd** [comment]
@Kagamine have you slept in the past 36 hours? :smile:

**Comment by Kagamine** [comment]
@caleblloyd Yep, my sleep time is 10:00PM CST to 7:30AM CST. It is 11:17AM now in China.

**Comment by caleblloyd** [comment]
@Kagamine I thought you stayed up all night working since you pushed 6 new builds in 24 hours haha

**Comment by mguinness** [comment]
@Kagamine I can confirm that 10009 fixed the issues that you mentioned.  Thank you so much, awesome work!
