### ISSUE TITLE
Revisiting charsets, beta-1

### ISSUE THREAD

**Issue by mc0re** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1402]
### Steps to reproduce
I have an old database created with default charset `latin1`. Pomelo _pre-5.0_ created tables with the same charset. But columns marked as `string` in code (and only those) were created using `utf8mb4` charset. This worked nicely, and I think it was a proper setup - as then the `CHAR(36)` columns I have for `Guid` type take 36 bytes, not 36x3 as if it was `utf8mb4` all the way.

Now the _beta-1_ version wants me to set up the database charset. If I set it to `latin1` (and do nothing else), it marks all columns to be `latin1` (saw in `AppDbContextModelSnapshot` and in the created migration). How can I persuade _Pomelo_ to keep my UTF-8 columns as UTF-8, without marking every single one of them as UTF-8?

### The issue
Here is a snippet of the created migration.
```
            migrationBuilder.AlterDatabase(
                collation: "latin1_swedish_ci")
                .Annotation("MySql:CharSet", "latin1")
                .OldAnnotation("MySql:CharSet", "utf8mb4");

            migrationBuilder.AlterTable(
                name: "NetworkDevices")
                .Annotation("MySql:CharSet", "latin1")
                .Annotation("Relational:Collation", "latin1_swedish_ci");

            migrationBuilder.AlterColumn<string>(
                name: "Description",
                table: "NetworkDevices",
                type: "longtext",
                nullable: false,
                collation: "latin1_swedish_ci",
                oldClrType: typeof(string),
                oldType: "longtext CHARACTER SET utf8mb4")
                .Annotation("MySql:CharSet", "latin1");
```

### Further technical details

Pomelo.EntityFrameworkCore.MySql version: 5.0.0-beta.1.ci.20210423124502
Microsoft.AspNetCore.App version: 5.0.5

**Comment by lauxjpn** [comment]
If you use `modelBuilder.HasCharSet("utf8mb4")`, all tables (meaning their default charset) and all columns that are mapped to a `System.String` will inherit the charset.

The columns that are mapped to a `System.Guid` property should not inherit the `utf8mb4` charset, even if they are represented by a `char(36)` store type.

**Comment by mc0re** [comment]
1. Using `modelBuilder.HasCharSet("utf8mb4")` and running the migration leads to a foreign constraint problem; one needs to use `SET FOREIGN_KEY_CHECKS=0` and the corresponding `SET ...=1` somehow.

2. The fix code you provided does not compile, as `HasCharSet()` expects an `EntityTypeBuilder`, `HasCollation` - a `PropertyBuilder`.

3. Mapping `Guid` to `char(36)` is a default behaviour, I don't know how to change it, and it's probably too late now that I have my PKs done as `Guid`s.

**Comment by lauxjpn** [comment]
> The fix code you provided does not compile, as HasCharSet() expects an EntityTypeBuilder, HasCollation - a PropertyBuilder.

Thanks, I just fixed the code (I wrote it from my had, without testing it). Should work now.

**Comment by mc0re** [comment]
> In your particular case...

Thanks for the code. Alas, that didn't help. I still get the foreign key error. Here is the migration snippet. Maybe, the problem is that `type` is specified, even though it's the same as `oldType`, thus `ALTER COLUMN` is executed. I tried the corresponding SQL directly, it only works if one disables the key check.

```
            migrationBuilder.AlterTable(
                name: "NetworkDevices")
                .Annotation("MySql:CharSet", "utf8mb4")
                .Annotation("Relational:Collation", "utf8mb4_unicode_520_ci");

            migrationBuilder.AlterColumn<Guid>(
                name: "SnapshotId",
                table: "NetworkDevices",
                type: "char(36)",
                nullable: false,
                oldClrType: typeof(Guid),
                oldType: "char(36)",
                oldCollation: "latin1_swedish_ci")
                .OldAnnotation("MySql:CharSet", "latin1");

            migrationBuilder.AlterColumn<string>(
                name: "Description",
                table: "NetworkDevices",
                type: "longtext",
                nullable: false,
                collation: "utf8mb4_unicode_520_ci",
                oldClrType: typeof(string),
                oldType: "longtext CHARACTER SET utf8mb4")
                .Annotation("MySql:CharSet", "utf8mb4");
```

**Comment by lauxjpn** [comment]
> Maybe, the problem is that `type` is specified, even though it's the same as `oldType`, thus `ALTER COLUMN` is executed.

That is possible. We will be releasing extension methods for precise control over the charset and collation delegation process. Those will allow to exactly keep the legacy behavior.

We will also add the explicit feature to use `ascii_general_ci` as the default collation for character based `Guid` columns, though I haven't decided yet whether we will ship this as part of 5.0 or 6.0.

**Comment by mc0re** [comment]
Thanks. I know how tedious at times it is to keep the backwards compatibility :-)
Will be waiting for the release to try that out. Will stay on `alpha` for the time being.
If you change the collation of `Guid` columns, please add the `SET FOREIGN_KEY_CHECKS`, otherwise it just won't work - at least in my setup.

**Comment by lauxjpn** [comment]
We have plans to add `SET FOREIGN_KEY_CHECKS` statements where appropriate in 6.0. I don't think it will make it into 5.0, so if anybody needs them in their migrations, they need to manually add them for now.

**Comment by lauxjpn** [comment]
@mc0re We will release `5.0.0-beta.2` in a couple of hours.
Feel free to test the latest [nightly build](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#nightly-builds) before that and report back to us whether everything works as expected now for you or not.

Use the following code to get the old `CharSet()` behavior:

```c#
// The following applies the "utf8mb4" charset recursively only to columns, without changing the default charset of
// the database or its tables.
modelBuilder.UseCharSet("utf8mb4", DelegationModes.ApplyToColumns);

// The following disables the newly introduced default collation 'ascii_general_ci' for character based Guid columns.
modelBuilder.UseGuidCollation(string.Empty);
```

**Comment by mc0re** [comment]
It's `HasCharSet()` this time :-)

**Comment by mc0re** [comment]
MariaDB gave me this message. I am not sure whether the rest of the migrations went through...

> ALTER DATABASE operations can currently not implicitly reset the character set AND the collation to the server default values. Please explicitly s
pecify a character set, a collation or both.

**Comment by lauxjpn** [comment]
> ```c#
> migrationBuilder.AlterDatabase()
>     .Annotation("MySql:CharSetDelegation", DelegationModes.ApplyToColumns)
>     .OldAnnotation("MySql:CharSet", "utf8mb4");
> ```

So the issue here is, that you are resetting your previously explicitly set charset (`utf8mb4`) to the server default. MySQL does not allow to directly use server variables like `@@character_set_server` in `ALTER DATABASE` statements. Usually, we would dynamically concatenate a string of the `ALTER DATABASE` statement and the character set and collation, and then just prepare and execute that command, but MySQL does not support the dynamic execution of the `ALTER DATABASE` statement.
Therefore, we have no way to reset the charset and collation to their respective defaults.

The message tells you, that if you want to explicitly reset the database charset and collation, you need to execute the statement yourself (e.g. using `Sql()` in your migration).
If you don't care about it, you can just ignore the warning.

However, I am wondering what happens, If just the delegation option is being changed, but not the character set and whether this would result in an ALTER DATABASE statement being generated. I will check that quickly, before we release `5.0.0-beta.2`.

**Comment by mc0re** [comment]
Thanks for the explanation. This can be remedied by using `DelegationModes.ApplyToDatabases`, right?
Would the default database charset influence future table creation?

**Comment by lauxjpn** [comment]
> Thanks for the explanation. This can be remedied by using `DelegationModes.ApplyToDatabases`, right?

Yes, setting an explicit database charset will result in a working ALTER DATABASE statement:

```c#
// Set the database charset to to "somecharset", but does not explicitly delegate it to tables or columns.
// If a table or column is created later, they will not explicitly use this charset. Instead, they will implicitly
// use whatever is the database charset at the time at the server (which will be "somecharset", unless it
// was changed in the meantime).
modelBuilder.HasCharSet("somecharset", DelegationModes.ApplyToDatabases);
```

For you scenario, where you want the string columns to be `utf8mb4_general_ci`, but the `Guid` columns to be `latin1_swedish_ci`, you could also use the following:

```c#
modelBuilder.UseCollation("utf8mb4_general_ci");
modelBuilder.UseGuidCollation("latin1_swedish_ci");
```
---

> Would the default database charset influence future table creation?

The default charset of the actual database (at the server) will only be used for future table creations, if you have not setup an explicit collation on your model (or on the table that is being created), that uses the `DelegationModes.ApplyToTables` flag.

**Comment by lauxjpn** [comment]
Alright, #1409 fixes migration operation related quirks.

**Comment by mc0re** [comment]
Thanks.
I figured that with my default charset `latin1` I cannot use `ascii_general_ci` collation, so I'll set it to what it is - `latin1_swedish_ci`. Which means that maybe when creating the `Guid` columns, you also ought to set the charset to `ascii`.

Is there an attribute for marking a property with a charset / collation? I have a few strings, which can only be ASCII (think promotion code or a MAC address)? I prefer attributes over `OnModelCreating`, as they are placed exactly where the thing is defined.

**Comment by lauxjpn** [comment]
> I figured that with my default charset `latin1` I cannot use `ascii_general_ci` collation, so I'll set it to what it is - `latin1_swedish_ci`. Which means that maybe when creating the `Guid` columns, you also ought to set the charset to `ascii`.

Generally, if you specify a collation and a charset, only the collation is being used by Pomelo for the column, as it already implies the charset (same when only specifying a collation). If only a charset is setup,

**Comment by mc0re** [comment]
> Please open a feature request issue

See https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1410.

**Comment by mc0re** [comment]
> to take precedence over the UseGuidCollation()...

Or you may want to be able to convert that column into the defined charset..?

**Comment by lauxjpn** [comment]
> When it comes to `UseGuidCollation()`, I think it currently takes precedence over a charset defined for that property, which is probably not how we want. I think if a charset (without a collation) is defined for a `Guid` property, we want that charset (and its default collation) to take precedence over the `UseGuidCollation()` defined collation. I have to check that.

It is indeed the case, that Pomelo will currently set the `UseGuidCollation()` collation together with an explicitly defined `HasCharSet()` charset on the migration operations (which is incorrect). I'll fix that quickly. The `5.0.0-beta.2` release will be released right after I merged the PR.

> Or you may want to be able to convert that column into the defined charset..?

No, there will be no explicit conversion happening. However, if you have an existing column in a specific charset an collation in your database at the server, and you define a different charset (and no collation) for the corresponding property in your Fluent API, we will generate the appropriate `ALTER TABLE MODIFY COLUMN CHARSET` command, that will let MySQL change the charset of that column to the one you specified, applying its default collation to it, and by doing so implicitly converting the data from the old charset to the new one.

**Comment by lauxjpn** [comment]
Okay, the final changes are pushed in #1411.
It mainly fixes the precedence issue (not just for `UseGuidCollation()`, but for `HasCharSet()` and `UseCollation()` as well), but also contains a pit of polishing.

@mc0re Thanks for the valuable feedback! This was quite productive.
