### ISSUE TITLE
EF Core 6 support

### ISSUE THREAD

**Issue by lauxjpn** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1413]
We will use this issue to track the progress on supporting EF Core 6, including its previews.

**Comment by lauxjpn** [comment]
With #1416, we have now full support for the upcoming **EF Core 6.0 Preview 4**.

The code quality should be as high as 5.0.0 GA, with all old and new tests working.
Therefore, the provider should run very stable.

We will push it to nuget when EF Core preview 4 gets released. Until then, use our [nightly builds](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#nightly-builds) together with the ones from EF Core. For the latter, add their feed to your [NuGet.config](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/NuGet.config) file (here with the key `dotnet6`):

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="pomelo" value="https://pkgs.dev.azure.com/pomelo-efcore/Pomelo.EntityFrameworkCore.MySql/_packaging/pomelo-efcore-public/nuget/v3/index.json" />
    <add key="dotnet6" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json" />
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
</configuration>
```

**Comment by mguinness** [comment]
Thanks for giving up your free time this past weekend to get this over the finish line.  Your hard work is very much appreciated.

Just a reminder to others that this is a community based project so if you are able to contribute either by helping with issues or with documentation that would also be appreciated.

**Comment by lauxjpn** [comment]
> One area we need help with is documenting both JSON and spatial queries. See [JSON Mapping](https://www.npgsql.org/efcore/mapping/json.html?tabs=data-annotations%2Cpoco) and [Spatial Mapping](https://www.npgsql.org/efcore/mapping/nts.html) as an example.

I'll attach the latest version of the function/method translations Excel file, that I use internally, to this post:

[Translations_20201231_01.xlsx](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/files/6488730/Translations_20201231_01.xlsx)

**Comment by lauxjpn** [comment]
[Prerelease](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/releases/tag/6.0.0-preview.4) `6.0.0-preview.4` is now available on [nuget.org](https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql/6.0.0-preview.4).

**Comment by lauxjpn** [comment]
While we dropped official support for MySQL 5.6 for the Pomelo 3.0.0 release about 2 years ago, we internally kept Pomelo as much compatible as possible to MySQL 5.6 anyway.

With MySQL 5.6 having officially reached its end-of-life earlier this year, Pomelo 6.0 will also drop unofficial support for it. This basically means, that we will no longer run our test suite for MySQL 5.6.

If you want to use Pomelo 6.0 and are currently using MySQL 5.6 (or even lower), strongly consider upgrading to at least MySQL 5.7.

**Comment by lauxjpn** [comment]
[Prerelease](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/releases/tag/6.0.0-preview.5) `6.0.0-preview.5` is now available on [nuget.org](https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql/6.0.0-preview.5).

**Comment by died** [comment]
So, ETA for rc1 ?

**Comment by danieramiz** [comment]
this still an issue?

**Comment by lauxjpn** [comment]
[Prerelease](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/releases/tag/6.0.0-preview.6) `6.0.0-preview.6` (compatible with EF Core 6.0 Preview 6) is now available on [nuget.org](https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql/6.0.0-preview.6).

**Comment by lauxjpn** [comment]
For anyone who is eager to use the latest EF Core release `6.0.0-rc.1.21452.10`:

We just pushed a [nightly build](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#nightly-builds) _prerelease_ `6.0.0-6.0.0-preview.7.ci.20211004193253` that, while officially targeting EF Core `6.0.0-preview.7.21378.4`, should also work with `6.0.0-rc.1.21452.10`.

**Comment by rodrigue10** [comment]
> For anyone who is eager to use the latest EF Core release `6.0.0-rc.1.21452.10`:
> 
> We just pushed a [nightly build](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#nightly-builds) _prerelease_ `6.0.0-6.0.0-preview.7.ci.20211004193253` that, while officially targeting EF Core `6.0.0-preview.7.21378.4`, should also work with `6.0.0-rc.1.21452.10`.

I just tried updating to `6.0.0-rc.1.21452.10` and still get this exception:
```
TypeLoadException: Method 'AppendIdentityWhereCondition' in type 'Pomelo.EntityFrameworkCore.MySql.Update.Internal.MySqlUpdateSqlGenerator' from assembly 'Pomelo.EntityFrameworkCore.MySql, Version=6.0.0.0, Culture=neutral, PublicKeyToken=2cc498582444921b' does not have an implementation.
```

Any information I can pass on to help with this?

**Comment by lauxjpn** [comment]
> I just tried updating to 6.0.0-rc.1.21452.10 and still get this exception: [...]

@rodrigue10 What are you trying to do at the moment this exception is being thrown? I compiled a simple console app that successfully executed a simple query against `6.0.0-rc.1.21452.10`. I did not test anything fancy yet.

**Comment by rodrigue10** [comment]
I'm using a '`BContextFactory` in my data service layer to inject my `DbContext` as needed in my app.
Then querying as needed to get the entities in question based on the service function.

As you mentioned, that `AppendIdentityWhereCondition()` method appears to be missing....I just downloaded the Pomelo source and seeing if there's something relatively easy to do here to get it up to snuff.

Example Snapshot of this implementation:
![image](https://user-images.githubusercontent.com/60077909/136041889-d679ce31-631d-42b9-b8fa-7f4ef2b2de6d.png)

**Comment by lauxjpn** [comment]
> As you mentioned, that `AppendIdentityWhereCondition()` method appears to be missing....I just downloaded the Pomelo source and seeing if there's something relatively easy to do here to get it up to snuff.

Just compiling it against EF Core `6.0.0-rc.1.21452.10` might be enought.

**Comment by lauxjpn** [comment]
Since the community seems to be eager to already use EF Core 6.0 RC1, we will not add anything else to the current EF Core 6.0 Preview 7 support and just publish it, and then provide a nightly build for EF Core 6.0 RC1.

**Comment by lauxjpn** [comment]
[Prerelease](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/releases/tag/6.0.0-preview.7) `6.0.0-preview.7` (compatible with EF Core 6.0 Preview 7) is now available on [nuget.org](https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql/6.0.0-preview.7).

Also, there is now the first _prerelease_ available on our [nightly build](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#nightly-builds) feed, that officially targets EF Core `6.0.0-rc.1.21452.10`.

**Comment by rodrigue10** [comment]
> [Prerelease](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/releases/tag/6.0.0-preview.7) `6.0.0-preview.7` (compatible with EF Core 6.0 Preview 7) is now available on [nuget.org](https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql/6.0.0-preview.7).
> 
> Also, there is now the first _prerelease_ available on our [nightly build](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#nightly-builds) feed, that officially targets EF Core `6.0.0-rc.1.21452.10`.

Awesome!  Thanks for all the hardwork!

**Comment by khteh** [comment]
.Net 6 is released next week. Any ETA for the GA?

**Comment by lauxjpn** [comment]
> .Net 6 is released next week. Any ETA for the GA?

Pomelo will publish its 6.0.0 GA release within 24 hours of the EF Core 6.0.0 GA release.

**Comment by lauxjpn** [comment]
Release [6.0.3](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/releases/tag/6.0.3) is now available on [nuget.org](https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql/6.0.3).
