### ISSUE TITLE
in 8.0.1 Is Timestamp byte[] no longer supported?

### ISSUE THREAD

**Issue by Clive321A** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1865]
### Steps to reproduce
add-migration myMigration

### The issue
I create a migration in 8.0.1, and it created a AlterColumn for every Identity column in my database, all like the below.
```
migrationBuilder.AlterColumn<int>(
    name: "Id",
    table: "RuleText",
    type: "int",
    nullable: false,
    oldClrType: typeof(int),
    oldType: "int")
    .Annotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);
```
it also created these in the ModelSnapShot file, 

MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime?>("Timestamp"));

When I tried to execute the migration it failed.

I have a base Entity Class defined like this.
```
    public abstract class Entity
    {
        [Required,Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        [Timestamp]
        public byte[] Timestamp { get; set; }
    }
```

Which all worked fine in 8.0.0.

It appears I need to change my TimeStamp to a DateTime column, which I deduced from what was being generated in the ModelSnapShot, which I did, and recreated the Migration, and the Migration now runs ok.

My question is, was that expected?, and will concurrency checking still work with the new Timestamp being a DateTime.?

It all seems to work (although hard to check concurrency errors), I'm just not sure if this is all intended,

### Further technical details

MySQL version: 
Operating system: Docker, linux
Pomelo.EntityFrameworkCore.MySql version: 8.0.1
Microsoft.AspNetCore.App version: net8.0

**Comment by lauxjpn** [comment]
@Clive321A We fixed a couple of issues with #1857, at least one was introduced in `8.0.1`.

Try the latest `8.0.2` [nightly build](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql?tab=readme-ov-file#nightly-builds) to check, whether your issue has already been fixed in it and report back to us. Thanks!

**Comment by Clive321A** [comment]
Thanks, I dont see a 8.0.2, I see 8.0.1 and then 9 Preview

![image](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/assets/29695733/9add4a15-3814-48eb-a52d-bcb7c48b06f3)

**Comment by lauxjpn** [comment]
@Clive321A Thanks for letting us know! Looks like we have missed in our CI to push packages from our maintenance branches to the nightly build feeds so far. We have now fixed this with @1867.

There should be now an `8.0.2` prerelease in the feeds.

**Comment by Clive321A** [comment]
HI, I still get that issue with 8.0.2

![image](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/assets/29695733/77727e88-fa0c-47dd-bf24-a6edf972a3d8)

I get these differences in the ModelSnapShot

![image](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/assets/29695733/a259383e-b3d1-4665-a8fc-69ab9e453e86)

![image](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/assets/29695733/a38b46fa-c70a-4165-beea-8dd4731752e4)

**Comment by lauxjpn** [comment]
@Clive321A My mistake, we hadn't backported the #1857 fix yet from our `main` branch into `8.0-maint`.

We have just done so now with #1869, so please try the latest `8.0.2` prerelease again from the [nightly build](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql?tab=readme-ov-file#nightly-builds) feeds.
It works fine in my tests with the model that you posted.

**Comment by Clive321A** [comment]
HI, Have tried with 8.0.2-servicing.1.ci.20240308012617 build, and get this error 

Unable to create a 'DbContext' of type 'DatabaseUnitOfWork'. The exception 'Computed value generation cannot be used for the property 'Timestamp' on entity type 'Extract' because the property type is 'byte[]'. Computed value generation can only be used with DateTime and DateTimeOffset properties.' was thrown while attempting to create an instance. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728

**Comment by lauxjpn** [comment]
> HI, Have tried with 8.0.2-servicing.1.ci.20240308012617 build, and get this error
> 
> Unable to create a 'DbContext' of type 'DatabaseUnitOfWork'. The exception 'Computed value generation cannot be used for the property 'Timestamp' on entity type 'Extract' because the property type is 'byte[]'. Computed value generation can only be used with DateTime and DateTimeOffset properties.' was thrown while attempting to create an instance. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728

I am unable to reproduce this issue with the following simple console program, that works as expected and isn't throwing an exception, neither during design time/adding new migrations nor during runtime when creating the context or querying:

<details>
<summary>Program.cs</summary>

```c#
using System;
using System.Diagnostics;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace IssueConsoleTemplate;

public class Entity
{
    public int Id { get; set; }
    public byte[] Timestamp { get; set; }
}

public class Context : DbContext
{
    public DbSet<Entity> Entities { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        if (!optionsBuilder.IsConfigured)
        {
            var connectionString = "server=127.0.0.1;port=3306;user=root;password=;database=Issue1865";
            var serverVersion = ServerVersion.AutoDetect(connectionString);

            optionsBuilder
                .UseMySql(connectionString, serverVersion)
                .LogTo(Console.WriteLine, LogLevel.Information)
                .EnableSensitiveDataLogging()
                .EnableDetailedErrors();
        }
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Entity>(
            entity =>
            {
                entity.Property(e => e.Timestamp)
                    .IsRowVersion();
                
                entity.HasData(
                    new Entity { Id = 1 },
                    new Entity { Id = 2 });
            });
    }
}

internal static class Program
{
    private static void Main()
    {
        using var context = new Context();
        
        // context.Database.EnsureDeleted();
        // context.Database.EnsureCreated();
        // context.Database.Migrate();

        var entities = context.Entities
            .OrderBy(e => e.Id)
            .ToList();
        
        Trace.Assert(entities.Count == 2);
        Trace.Assert(entities[0].Id == 1);
        Trace.Assert(entities[1].Id == 2);
    }
}
```

</details>

I use Pomelo `8.0.0` and `dotnet-ef` `8.0.0` to run the following CLI command:

```
dotnet ef migrations add 'Pomelo800'
```

It creates the following files without throwing an exception:

<details>
<summary>20240308081054_Pomelo800.cs</summary>

```c#
using System;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace IssueConsoleTemplate.Migrations
{
    /// <inheritdoc />
    public partial class Pomelo800 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterDatabase()
                .Annotation("MySql:CharSet", "utf8mb4");

            migrationBuilder.CreateTable(
                name: "Entities",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn),
                    Timestamp = table.Column<DateTime>(type: "timestamp(6)", rowVersion: true, nullable: true)
                        .Annotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.ComputedColumn)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Entities", x => x.Id);
                })
                .Annotation("MySql:CharSet", "utf8mb4");

            migrationBuilder.InsertData(
                table: "Entities",
                column: "Id",
                values: new object[]
                {
                    1,
                    2
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Entities");
        }
    }
}
```

</details>

<details>
<summary>20240308081054_Pomelo800.Designer.cs</summary>

```c#
// <auto-generated />
using System;
using IssueConsoleTemplate;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IssueConsoleTemplate.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20240308081054_Pomelo800")]
    partial class Pomelo800
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("IssueConsoleTemplate.Entity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)");

                    b.HasKey("Id");

                    b.ToTable("Entities");

                    b.HasData(
                        new
                        {
                            Id = 1
                        },
                        new
                        {
                            Id = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
```

</details>

I use Pomelo `8.0.2-servicing.1.ci.20240308012617.debug` and `dotnet-ef` `8.0.2` to run the following CLI command:

```
dotnet ef migrations add 'Pomelo802a'
```

It creats the following files without throwing an exception:

<details>
<summary>20240308081545_Pomelo802a.cs</summary>

```c#
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace IssueConsoleTemplate.Migrations
{
    /// <inheritdoc />
    public partial class Pomelo802a : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<int>(
                name: "Id",
                table: "Entities",
                type: "int",
                nullable: false,
                oldClrType: typeof(int),
                oldType: "int")
                .Annotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<int>(
                name: "Id",
                table: "Entities",
                type: "int",
                nullable: false,
                oldClrType: typeof(int),
                oldType: "int")
                .OldAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);
        }
    }
}
```

</details>

<details>
<summary>20240308081545_Pomelo802a.Designer.cs</summary>

```c#
// <auto-generated />
using System;
using IssueConsoleTemplate;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IssueConsoleTemplate.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20240308081545_Pomelo802a")]
    partial class Pomelo802a
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("IssueConsoleTemplate.Entity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)");

                    b.HasKey("Id");

                    b.ToTable("Entities");

                    b.HasData(
                        new
                        {
                            Id = 1
                        },
                        new
                        {
                            Id = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
```

</details>

Still using Pomelo `8.0.2-servicing.1.ci.20240308012617.debug` and `dotnet-ef` `8.0.2`, I run the following CLI command, just to make sure that this will create an empty migration. The migration should be empty because there was no model change and no Pomelo version change:

```
dotnet ef migrations add 'Pomelo802b'
```

It indeed creates the following empty migration files without throwing an exception:

<details>
<summary>20240308082021_Pomelo802b.cs</summary>

```c#
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace IssueConsoleTemplate.Migrations
{
    /// <inheritdoc />
    public partial class Pomelo802b : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {

        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
```

</details>

<details>
<summary>20240308082021_Pomelo802b.Designer.cs</summary>

```c#
// <auto-generated />
using System;
using IssueConsoleTemplate;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IssueConsoleTemplate.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20240308082021_Pomelo802b")]
    partial class Pomelo802b
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("IssueConsoleTemplate.Entity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)");

                    b.HasKey("Id");

                    b.ToTable("Entities");

                    b.HasData(
                        new
                        {
                            Id = 1
                        },
                        new
                        {
                            Id = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
```

</details>

Still using Pomelo `8.0.2-servicing.1.ci.20240308012617.debug` and `dotnet-ef` `8.0.2`, I run the following CLI command to create and update the database:

```
dotnet ef database update
```

It generates the following output without throwing an exception and sucessfully creates the database:

<details>
<summary>Output (SQL)</summary>

```sql
warn: 08.03.2024 09:25:34.155 CoreEventId.SensitiveDataLoggingEnabledWarning[10400] (Microsoft.EntityFrameworkCore.Infrastructure) 
      Sensitive data logging is enabled. Log entries and exception messages may include sensitive application data; this mode should only be enabled dur
ing development.
info: 08.03.2024 09:25:34.363 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command) 
      Executed DbCommand (10ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      CREATE DATABASE `Issue1865`;
info: 08.03.2024 09:25:34.463 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command) 
      Executed DbCommand (28ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      CREATE TABLE `__EFMigrationsHistory` (
          `MigrationId` varchar(150) CHARACTER SET utf8mb4 NOT NULL,
          `ProductVersion` varchar(32) CHARACTER SET utf8mb4 NOT NULL,
          CONSTRAINT `PK___EFMigrationsHistory` PRIMARY KEY (`MigrationId`)
      ) CHARACTER SET=utf8mb4;
info: 08.03.2024 09:25:34.479 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (4ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='Issue1865' AND TABLE_NAME='__EFMigrationsHistory';
info: 08.03.2024 09:25:34.483 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (2ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT `MigrationId`, `ProductVersion`
      FROM `__EFMigrationsHistory`
      ORDER BY `MigrationId`;
Applying migration '20240308081054_Pomelo800'.
info: 08.03.2024 09:25:34.494 RelationalEventId.MigrationApplying[20402] (Microsoft.EntityFrameworkCore.Migrations)
      Applying migration '20240308081054_Pomelo800'.
info: 08.03.2024 09:25:34.523 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command) 
      Executed DbCommand (6ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      ALTER DATABASE CHARACTER SET utf8mb4;
info: 08.03.2024 09:25:34.552 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command) 
      Executed DbCommand (28ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      CREATE TABLE `Entities` (
          `Id` int NOT NULL AUTO_INCREMENT,
          `Timestamp` timestamp(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
          CONSTRAINT `PK_Entities` PRIMARY KEY (`Id`)
      ) CHARACTER SET=utf8mb4;
info: 08.03.2024 09:25:34.560 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (7ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      INSERT INTO `Entities` (`Id`)
      VALUES (1),
      (2);
info: 08.03.2024 09:25:34.565 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command) 
      Executed DbCommand (5ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      INSERT INTO `__EFMigrationsHistory` (`MigrationId`, `ProductVersion`)
      VALUES ('20240308081054_Pomelo800', '8.0.2');
Applying migration '20240308081545_Pomelo802a'.
info: 08.03.2024 09:25:34.566 RelationalEventId.MigrationApplying[20402] (Microsoft.EntityFrameworkCore.Migrations)
      Applying migration '20240308081545_Pomelo802a'.
info: 08.03.2024 09:25:34.581 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command) 
info: 08.03.2024 09:25:34.587 RelationalEventId.MigrationApplying[20402] (Microsoft.EntityFrameworkCore.Migrations)
      Applying migration '20240308082021_Pomelo802b'.
info: 08.03.2024 09:25:34.591 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      INSERT INTO `__EFMigrationsHistory` (`MigrationId`, `ProductVersion`)
      VALUES ('20240308082021_Pomelo802b', '8.0.2');
Done.
```

</details>

I run the sample app:

```
dotnet run
```

It generates the following output without throwing an exception:

<details>
<summary>Output (SQL)</summary>

```sql
warn: 08.03.2024 09:29:06.664 CoreEventId.SensitiveDataLoggingEnabledWarning[10400] (Microsoft.EntityFrameworkCore.Infrastructure) 
      Sensitive data logging is enabled. Log entries and exception messages may include sensitive application data; this mode should only be enabled dur
ing development.
info: 08.03.2024 09:29:06.928 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command) 
      Executed DbCommand (10ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT `e`.`Id`, `e`.`Timestamp`
      FROM `Entities` AS `e`
      ORDER BY `e`.`Id`
```

</details>

So using the model that you posted earlier, I am not able to reproduce the exception that you reported.

@Clive321A Please verify that the sample code I posted works on your end as well. Then change it, so it reproduces the exception that you are getting in your own code. Thanks!

**Comment by Clive321A** [comment]
as an asside, are the annotations not required on Entity for IdentityColumn

If I remove, it still recognises it as the Identity column, I guess by convention, but Timestamp has to be used, OR use isRowVersion in modelcreating.

```
    public abstract class Entity
    {
     //   [Required,Key]
     //   [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        [Timestamp]
        public byte[] Timestamp { get; set; }
    }
```

```
            foreach (var entityType in modelBuilder.Model.GetEntityTypes())
            {
                var timestampProperty = entityType.FindProperty("Timestamp");

                if (timestampProperty != null)
                {
                    modelBuilder.Entity(entityType.ClrType).Property("Timestamp").IsRowVersion(); 
                 //   timestampProperty.AddAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.ComputedColumn);
                }
            }
```

**Comment by lauxjpn** [comment]
@Clive321A Thanks for letting us know!

> From looking at the migration, it does appear to be doing nothing though?

In that case, there is probably just a metadata change (correcting the metadata is one of the fixes). If you diff the `*.Designer.cs` files of the previous and the new migration, there should be a difference. In cases like that, where only the metadata changes, and the `Up()` and `Down()` methods don't really do anything, you could just remove the operations from the `Up()` and `Down()` methods if you want.

> I forgot all about this below in my ModelCreating , there was an issue with migrations about a year ago in issue 1757, so I had put this in to resolve it.

Yes, I stumbled across this issue while reproducing #1774 and therefor fixed both issues together. I was not aware that this had already been reported, so I'll update the issues and PRs to reflect the fact that #1774 has now been fixed as well.

> If I remove, it still recognises it as the Identity column, I guess by convention [...]

That is correct. The `Id` property is marked as a primary key by EF Core by convention. Because the key has a type that is compatible with MySQL `auto_increment` colums, Pomelo then annotates the property with `MySqlValueGenerationStrategy.IdentityColumn` via convention as well, which then makes it an `auto_increment` column. So there is no need to mark it manually. It the PK property name would be exotic (e.g. `MyKee`), then you would need to tell EF Core, that this is a primary key (e.g. by using the `KeyAttribute` or a `.HasKey()` Fluent API call). That alone would usually be enough then, to make it an `auto_increment` column as well.

> [...] but Timestamp has to be used, OR use isRowVersion in modelcreating.

Indeed.  The `TimestampAttribute` is the same as using a `.IsRowVersion()` Fluent API call. I believe there is no convention for making a property a `RowVersion` (though I have never checked), so you have to explicitly specify that a property should be used in that way.

**Comment by Clive321A** [comment]
Great thanks for your help, all good now.
