### ISSUE TITLE
charset settings may cause memory leak

### ISSUE THREAD

**Issue by HangJiang** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#619]
### Steps to reproduce
when configure AddDbContext like this:
` services.AddDbContext<TContext>(options => options.UseMySql(dbConnectString,
                opt =>
                {
                    opt.CharSetBehavior(Pomelo.EntityFrameworkCore.MySql.Infrastructure.CharSetBehavior.AppendToAllColumns)
                        .AnsiCharSet(Pomelo.EntityFrameworkCore.MySql.Infrastructure.CharSet.Utf8mb4)
                        .UnicodeCharSet(Pomelo.EntityFrameworkCore.MySql.Infrastructure.CharSet.Utf8mb4);
                }));`

use options to config charset.

### The issue

charset options  will cause warning:

> “warn: Microsoft.EntityFrameworkCore.Infrastructure[10402]
>      More than twenty 'IServiceProvider' instances have been created for internal use by Entity >Framework. This is commonly caused by injection of a new singleton service instance into every >DbContext instance. For example, calling UseLoggerFactory passing in a new instance each time--see >https://go.microsoft.com/fwlink/?linkid=869049 for more details. Consider reviewing calls on >'DbContextOptionsBuilder' that may require new service providers to be built.”

remove the charset options will be ok

```
Exception message:
Stack trace:
```

### Further technical details

MySQL version: 5.7
Operating system: centos 7
Pomelo.EntityFrameworkCore.MySql version:2.1.0-rc1-final

**Comment by caleblloyd** [comment]
Fixed in [2.1.0-rc2-final](https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql/2.1.0-rc2-final)

**Comment by XuluniX** [comment]
This issue still exists in Version 2.1.2-preview1-2018071119475.
If charset settings are removed, everything works like expected, if they are set instances start to leak.
